### ISSUE TITLE
Add minimal set of projects for which JDBL doesn't work

### ISSUE THREAD

**Issue by cesarsotovalero** [castor-software/jdbl#8]
It's hard to analyze the results of JDBL on a large set of projects because it takes too much time to run. Therefore, we need to create a minimal set of projects that are failing the tests on the debloated library, and for which the client doesn't compile. This way, we should be able to fix the problems one at the time, and improve JDBL incrementally.

**Comment by bbaudry** [comment]
> Therefore, we need to create a minimal set of projects that are failing the tests on the debloated library, and for which the client doesn't compile.

I suggest to forget about clients for the moment and focus on the libraries that we debloat
For each of them
- experiment various strategies for trace-based debloating, from the most conservative to the most agressive
- what are the debloated versions that pass the same tests as the original?
  - what are these different strategies
  - what parts of the code do we systematically leave in, whatever the coverage information?
- why do some debloated versions fail the tests?
- for each debloated version what is the ratio of code that we did not remove even though it was marked as uncovered by jacoco?

**Comment by cesarsotovalero** [comment]
Done in https://github.com/castor-software/jdbl-experiments.
